In [39]:
import numpy as np
import math

In [40]:
graph={
    1:[2],
    2:[1,4],
    3:[4,5],
    4:[2,3,5],
    5:[3,4]
}

In [41]:
ADJ_MAT=[[0 for _ in range(len(graph))] for _ in range(len(graph))]
ADJ_MAT

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [42]:
for i in graph:
    if graph[i]:
        for j in graph[i]:
            print(i-1,j-1)
            ADJ_MAT[i-1][j-1]=1

0 1
1 0
1 3
2 3
2 4
3 1
3 2
3 4
4 2
4 3


In [43]:
ADJ_MAT

[[0, 1, 0, 0, 0],
 [1, 0, 0, 1, 0],
 [0, 0, 0, 1, 1],
 [0, 1, 1, 0, 1],
 [0, 0, 1, 1, 0]]

In [44]:
EIG_MAT=[[1] for _ in range(len(graph))]
EIG_MAT

[[1], [1], [1], [1], [1]]

In [45]:
res=np.dot(ADJ_MAT,EIG_MAT)
res

array([[1],
       [2],
       [2],
       [3],
       [2]])

In [46]:
def get_normalized_value(res):
    sum=0
    for n in res:
        sum=sum+(n*n)
    return round(math.sqrt(sum),3)

In [47]:
norm_val_diff=float('inf')
old_norm_val=0
i=0
while norm_val_diff>0.01:
    i+=1
    res=np.dot(ADJ_MAT,EIG_MAT)
    norm_val=get_normalized_value(res)
    new_res=res/norm_val
    print(f'Eigent vectors @ iteration #{i} \n{new_res}')
    print(norm_val,old_norm_val)
    norm_val_diff=abs(norm_val-old_norm_val)
    old_norm_val=norm_val
    EIG_MAT=new_res

Eigent vectors @ iteration #1 
[[0.21321962]
 [0.42643923]
 [0.42643923]
 [0.63965885]
 [0.42643923]]
4.69 0
Eigent vectors @ iteration #2 
[[0.19427755]
 [0.38855511]
 [0.48569389]
 [0.58283266]
 [0.48569389]]
2.195 4.69
Eigent vectors @ iteration #3 
[[0.17573727]
 [0.35147454]
 [0.4832775 ]
 [0.61508045]
 [0.4832775 ]]
2.211 2.195
Eigent vectors @ iteration #4 
[[0.15882266]
 [0.35735098]
 [0.49632081]
 [0.59558497]
 [0.49632081]]
2.213 2.211
